In [1]:
from bell import *

In [2]:
w = [[2,2], [2,2]]
D = construct_deterministic_behaviors(w)

In [5]:
bell_functional, classical_bound = chsh_inequality()
observables, state = example_chsh_saturator()
p = quantum_behavior_from_povms(construct_povms_from_observables(observables), state)
assert np.isclose(bell_functional @ p, 2*np.sqrt(2))

In [6]:
is_facet_inequality(D, *chsh_inequality())

(np.True_,
 {'dim_polytope': np.int64(8),
  'dim_face': np.int64(7),
  'num_saturating': 8,
  'saturating_indices': array([ 0,  1,  4,  6,  9, 11, 14, 15])})

## Dichotomous

In [7]:
bell_functional, classical_bound = construct_bell_inequality(w, p, dichotomous=True)
bell_functional, classical_bound

(array([ 1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,
         1.,  1., -1.]),
 array(2.))

In [8]:
bell_functional @ p, 2*np.sqrt(2)

(np.float64(2.828427124746189), np.float64(2.8284271247461903))

In [9]:
D @ bell_functional

array([ 2.,  2., -2., -2.,  2., -2.,  2., -2., -2.,  2., -2.,  2., -2.,
       -2.,  2.,  2.])

In [10]:
is_facet_inequality(D, bell_functional, classical_bound)

(np.True_,
 {'dim_polytope': np.int64(8),
  'dim_face': np.int64(7),
  'num_saturating': 8,
  'saturating_indices': array([ 0,  1,  4,  6,  9, 11, 14, 15])})

## Nondichotomous

In [11]:
bell_functional, classical_bound = construct_bell_inequality(w, p, dichotomous=False)
bell_functional, classical_bound

(array([ 3.695, -7.351, -7.351,  3.695,  3.695, -7.351, -7.351,  3.695,
         3.695, -7.351, -7.351,  3.695, -7.351,  3.695,  3.695, -7.351]),
 array(7.311))

In [12]:
bell_functional @ p

np.float64(8.310541292888681)

In [13]:
D @ bell_functional

array([  3.735,   3.735, -18.356, -18.356,   3.735, -18.356,   3.735,
       -18.356, -18.356,   3.735, -18.356,   3.735, -18.356, -18.356,
         3.735,   3.735])

In [14]:
is_facet_inequality(D, bell_functional, classical_bound)

(False,
 {'reason': 'No deterministic vertices saturate the inequality.',
  'dim_polytope': None,
  'dim_face': None,
  'num_saturating': 0,
  'saturating_indices': []})