In [1]:
from bell import *

In [17]:
n_parties = 2 # parties
n_measurements = 2 # number of measurements
n_outcomes = [2, 2] # number of outcomes
D = construct_deterministic_behaviors(n_parties, n_measurements, n_outcomes)

In [18]:
bell_functional, classical_bound = chsh_inequality()
observables, state = example_chsh_saturator()
p, labels = construct_p(observables, state, labels=True)
assert np.isclose(bell_functional @ p, 2*np.sqrt(2))

In [19]:
is_facet_inequality(D, *chsh_inequality())

(np.True_,
 {'dim_polytope': np.int64(8),
  'dim_face': np.int64(7),
  'num_saturating': 8,
  'saturating_indices': array([ 0,  1,  4,  6,  9, 11, 14, 15])})

## Dichotomous

In [20]:
bell_functional, classical_bound = construct_bell_inequality(n_parties, n_measurements, n_outcomes, p, dichotomous=True)
bell_functional, classical_bound

(array([ 1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,
         1.,  1., -1.]),
 array(2.))

In [21]:
bell_functional @ p, 2*np.sqrt(2)

(np.float64(2.828427124746189), np.float64(2.8284271247461903))

In [22]:
D @ bell_functional

array([ 2.,  2., -2., -2.,  2., -2.,  2., -2., -2.,  2., -2.,  2., -2.,
       -2.,  2.,  2.])

In [23]:
is_facet_inequality(D, bell_functional, classical_bound)

(np.True_,
 {'dim_polytope': np.int64(8),
  'dim_face': np.int64(7),
  'num_saturating': 8,
  'saturating_indices': array([ 0,  1,  4,  6,  9, 11, 14, 15])})

## Nondichotomous

In [24]:
bell_functional, classical_bound = construct_bell_inequality(n_parties, n_measurements, n_outcomes, p, dichotomous=False)
bell_functional, classical_bound

(array([ 3.695, -7.351, -7.351,  3.695,  3.695, -7.351, -7.351,  3.695,
         3.695, -7.351, -7.351,  3.695, -7.351,  3.695,  3.695, -7.351]),
 array(7.311))

In [25]:
bell_functional @ p

np.float64(8.310541292888681)

In [26]:
D @ bell_functional

array([  3.735,   3.735, -18.356, -18.356,   3.735, -18.356,   3.735,
       -18.356, -18.356,   3.735, -18.356,   3.735, -18.356, -18.356,
         3.735,   3.735])

In [27]:
is_facet_inequality(D, bell_functional, classical_bound)

(False,
 {'reason': 'No deterministic vertices saturate the inequality.',
  'dim_polytope': None,
  'dim_face': None,
  'num_saturating': 0,
  'saturating_indices': []})