In [65]:
import numpy as np
import scipy as sc
import mpmath as mp
np.set_printoptions(precision=3, suppress=True)

from cirq_sic import *

In [91]:
d = 4
globals().update(wh_operators(d))
phi = np.array([complex(mp.jtheta(3, np.pi*k/d, np.exp(-np.pi/d))) for k in range(d)])
phi = phi/np.linalg.norm(phi); phi

array([0.838+0.j, 0.383+0.j, 0.072+0.j, 0.383+0.j])

In [92]:
assert np.allclose(F @ phi, phi)

In [93]:
E = wh_povm(phi)
P = np.array([[(a@b).trace()/b.trace() for b in E] for a in E]).real; P

array([[ 0.25 ,  0.121,  0.043,  0.121,  0.121,  0.043, -0.   ,  0.043,
         0.043,  0.   ,  0.007,  0.   ,  0.121,  0.043, -0.   ,  0.043],
       [ 0.121,  0.25 ,  0.121,  0.043,  0.043,  0.121,  0.043, -0.   ,
         0.   ,  0.043,  0.   ,  0.007,  0.043,  0.121,  0.043, -0.   ],
       [ 0.043,  0.121,  0.25 ,  0.121, -0.   ,  0.043,  0.121,  0.043,
         0.007,  0.   ,  0.043,  0.   , -0.   ,  0.043,  0.121,  0.043],
       [ 0.121,  0.043,  0.121,  0.25 ,  0.043, -0.   ,  0.043,  0.121,
         0.   ,  0.007,  0.   ,  0.043,  0.043, -0.   ,  0.043,  0.121],
       [ 0.121,  0.043, -0.   ,  0.043,  0.25 ,  0.121,  0.043,  0.121,
         0.121,  0.043,  0.   ,  0.043,  0.043,  0.   ,  0.007,  0.   ],
       [ 0.043,  0.121,  0.043, -0.   ,  0.121,  0.25 ,  0.121,  0.043,
         0.043,  0.121,  0.043,  0.   ,  0.   ,  0.043,  0.   ,  0.007],
       [-0.   ,  0.043,  0.121,  0.043,  0.043,  0.121,  0.25 ,  0.121,
         0.   ,  0.043,  0.121,  0.043,  0.007,  0.   ,  0

In [94]:
np.linalg.eigvals(P)

array([ 1.   ,  0.029, -0.   ,  0.485,  0.485,  0.485,  0.485, -0.   ,
        0.172,  0.172,  0.   , -0.   ,  0.172,  0.172,  0.172,  0.172])

In [95]:
phi.conj() @ X @ phi, phi.conj() @ Z @ phi

(np.complex128(0.696621399498013-5.3134387781020967e-17j),
 np.complex128(0.6966213994980132+8.326672684688674e-17j))

In [100]:
delta_X2 = 1 - abs(phi.conj() @ X @ phi)**2
delta_Z2 = 1 - abs(phi.conj() @ Z @ phi)**2
delta_X2*delta_Z2, np.pi**2/d**2

(np.float64(0.26493526370573467), 0.6168502750680849)