In [1]:
from cirq_sic import *
from cirq.contrib.svg import SVGCircuit

# https://github.com/pifparfait/Efficient-Quantum-Modular-Arithmetics/blob/main/quantum_modular_artihmetics.ipynb

In [2]:
def F(q):
    yield cirq.qft(*q, without_reverse=False)

def Fdag(q):
    yield cirq.qft(*q, inverse=True, without_reverse=False)

def add_k(q, k):
    """
    Apply a rotation gate to each qubit in q rotating by an angle 'k * pi / 2^j'.
    """
    n = len(q)
    for j in range(n):
        angle = k * np.pi  / (2**j)
        yield cirq.Rz(rads=angle)(q[j])

def controlled_add_k(q, c, k):
    n = len(q)
    for j in range(n):
        angle = k * np.pi  / (2**j)
        yield cirq.Rz(rads=angle).on(q[j]).controlled_by(c)

def add_k_mod_d(q, c, k, d, is_in_standard_basis=True):
    """
    Perform in-place modular addition of 'k' modulo d to the qubits in q. c is an auxiliary qubit.
    'is_in_standard_basis' specifies whether the input state is in the standard basis (True) or Fourier basis (False).
    """
    sig_bit = q[0]

    # Set the Fourier basis if 'is_in_standard_basis' is True
    if is_in_standard_basis:
        yield F(q)
    
    # Step 1: Add 'k' to the register
    yield add_k(q, k)
    
    # Step 2: Subtract 'd'
    yield add_k(q, -d)
    
    # Step 3: Conditionally add 'd' back
    yield Fdag(q)
    yield cirq.CNOT(sig_bit, c)
    yield F(q)

    # Step 4: Add 'd' to the register conditionally
    yield controlled_add_k(q, c, d)
    
    # Step 5: Clear the auxiliary bit
    yield add_k(q, -k)
    
    # Step 6: Conditionally add 'd' back
    yield Fdag(q)
    yield cirq.X(sig_bit)
    yield cirq.CNOT(sig_bit, c)  # Use the most significant bit to control the auxiliary bit
    yield cirq.X(sig_bit)
    yield F(q) 

    # Step 7: Add 'k' to the register
    yield add_k(q, k)
    
    # Recover the standard basis if 'is_in_standard_basis' is True
    if is_in_standard_basis:
        yield Fdag(q)

n = 3
d = 3
q = cirq.LineQubit.range(n)
c = cirq.NamedQubit("cntrl")
circ = cirq.Circuit((add_k_mod_d(q, c, 2, d)))
sim = cirq.Simulator()
ket = rand_ket(d)
initial_state = np.kron(np.concatenate([ket, np.zeros(2**n-d)]), np.eye(2)[0])
result = sim.simulate(circ, initial_state=initial_state, qubit_order=q+[c])
result.density_matrix_of(q)[:d, :d], np.diag(result.density_matrix_of([c]))

(array([[ 0.194+0.j   ,  0.176-0.211j, -0.173-0.225j],
        [ 0.176+0.211j,  0.391+0.j   ,  0.087-0.393j],
        [-0.173+0.225j,  0.087+0.393j,  0.415+0.j   ]], dtype=complex64),
 array([1.+0.j, 0.+0.j], dtype=complex64))

In [3]:
np.outer(ket,ket.conj())

array([[ 0.415-0.j   , -0.141-0.246j, -0.397-0.07j ],
       [-0.141+0.246j,  0.194-0.j   ,  0.176-0.211j],
       [-0.397+0.07j ,  0.176+0.211j,  0.391-0.j   ]])

This modular addition algorithm works by temporarily calculating values like a+k. Since a and k can both be as large as d-1, their sum can reach up to (d-1) + (d-1) = 2d-2.

Your qubit register can only represent integers from 0 to $2^n-1$. For the algorithm's logic (especially the part that checks for overflow using the most significant bit) to be reliable, the temporary sum must not exceed the register's capacity.

This leads to the requirement: $2d-2 < 2^n$. Thus we can encode a qudit in $n$ qubits with $d$ satisfying

$$d \leq 2^{n-1}  $$

In [4]:
import inspect

def make_controlled_version_recursive(control_qubit, circuit_generator):
    """
    Recursively unpacks nested generators and applies a control
    to every operation.
    """
    # Iterate through all items yielded by the generator
    for item in circuit_generator:
        # Case 1: The item is a standard Cirq Operation
        if isinstance(item, cirq.Operation):
            yield item.controlled_by(control_qubit)
        # Case 2: The item is another generator
        elif inspect.isgenerator(item):
            # If so, recursively call this function on the sub-generator
            # and yield all of its controlled operations.
            yield from make_controlled_version_recursive(control_qubit, item)
        # You could add other cases here if needed (e.g., for lists of ops)

In [5]:
def add_mod_d(d, c, t, aux1, aux2):
    new_t = [aux1] + t
    yield F(new_t)
    for i in range(len(c)):
        k = 2**(len(c) - 1 - i) % d
        yield make_controlled_version_recursive(c[i], add_k_mod_d(new_t, aux2, k, d, is_in_standard_basis=False) )
    yield Fdag(new_t)

In [13]:
n = 2
d = 2
c = cirq.LineQubit.range(n)
t = cirq.LineQubit.range(n, 2*n)
aux1 = cirq.NamedQubit("aux1")
aux2 = cirq.NamedQubit("aux2")

circ = cirq.Circuit((add_mod_d(d, c, t, aux1, aux2)))

In [18]:
a = 1
b = 1
initial_state = kron(np.eye(2**n)[a],np.eye(2**n)[b],np.eye(4)[0])
final_state = kron(np.eye(2**n)[a],np.eye(2**n)[(a+b)%d])
sim = cirq.Simulator()
result = sim.simulate(circ, initial_state=initial_state, qubit_order=c+t+[aux1, aux2])
res_vec = np.diag(result.density_matrix_of(c+t)).real
res_vec, final_state

(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))