In [1]:
from cirq_sic import *

In [24]:
d_s = 2
d_b = 3
w_s = np.exp(2*np.pi*1j/d_s)
w_b = np.exp(2*np.pi*1j/d_b)
Z = np.diag([w_s**i for i in range(d)]+[1]*(d_b-d_s)); Z

array([[ 1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [30]:
F = np.array([[w_s**(i*j) for j in range(d_b)] for i in range(d_b)])/np.sqrt(d_b); F

array([[ 0.577+0.j,  0.577+0.j,  0.577+0.j],
       [ 0.577+0.j, -0.577+0.j,  0.577-0.j],
       [ 0.577+0.j,  0.577-0.j,  0.577-0.j]])

In [31]:
F.conj().T @ Z @ F

array([[0.333+0.j, 1.   -0.j, 0.333-0.j],
       [1.   +0.j, 0.333+0.j, 1.   -0.j],
       [0.333+0.j, 1.   +0.j, 0.333+0.j]])

In [32]:
X = np.array([[0,1,0],[1,0,0], [0,0,1]]); X

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [33]:
F @ X @ F.conj().T

array([[ 1.   +0.j,  0.333+0.j,  1.   +0.j],
       [ 0.333-0.j, -0.333-0.j,  0.333+0.j],
       [ 1.   -0.j,  0.333-0.j,  1.   -0.j]])